= To Do

* [ ] Basic MVP functionality.
** [x] Load from TOML file.
*** [x] Logic
*** [x] CLI
** [ ] Write to TOML file.
*** [ ] Logic
*** [ ] CLI
* [ ] Command `self` to activate shell completion according to directions at: https://click.palletsprojects.com/en/8.1.x/shell-completion/
* [ ] Multiple TOML files for, e.g., version control in separate repos.
** [ ] Allow users to register multiple file paths for different docs. These dirs could conceivably be in Git repos, or other kinds of VCS repos.
** [ ] Have a config variable for the default store location.
* [ ] Sugar for pushing/pulling updates via Git (and possibly other VCSes).
** [ ] Decide whether to support Git only, or other VCSes as well.
** [ ] Document the decision.
* [ ] Groups or tags to associate acronyms with each other and facilitate sorting/filtering. Could be implemented as another field in the TOML, an array of strings.
** [ ] Could be used to allow transferring entire groups to other TOML files.
** [ ] Ability to reorganize (merge, delete, rename) groups without data loss.
* [ ] Allow multiple reference links.
* [ ] Links to alternate meanings of the same acronym.
* [ ] Links to alternate acronyms with the same meaning. (E.g. Inverter-Based Resource (IBR) and Converter Interfaced Generation (CIG))
* [ ] "As opposed to" field to help find related acronyms/terms.
// cspell:ignore QSPI
* [ ] "See also" links to related acronyms. Esp. intended for acronyms that are slight variations of each other, such as SPI and QSPI.
* [ ] Preferred reference config option. Allow users to specify their preferred reference source, whether Wikipedia, TechTarget, etc. This might involve either (a) dynamically fetching definitions or (b) storing multiple references based on different sources.
* [ ] Consider allowing combining all acronyms and persistent state in one file in USER_DATA_DIR, esp. if performance of having to open multiple files for a single command is an issue.
* [ ] A `check` command of sorts
** [ ] Check integrity of a given TOML file.
** [ ] Check for incompletion of acronyms, e.g. flag ones that don't have all fields filled. Could possibly allow to ignore certain incomplete ones. Possibly rank by number of missing fields.
** [ ] Check for any definitions that contain other acronyms which are not defined.
* [ ] While viewing, if an acronym definition contains other acronyms, allow the option to expand those out within the parent definition so users don't have to go search another layer deeper.
* [ ] Recognize acronyms contained in other acronym definitions.
** [ ] If the user inputs such a definition that spells out the dependency acronym (e.g. the CHAP Wikipedia page mentions PPP as "Point-to-Point Protocol (PPP)"), they should be prompted to make another entry for that acronym, with fields automatically pre-filled based on what they entered. This is an attempt to get the user to document acronyms used in other acronym definitions.
*** [ ] Have a `--force` option to override such restrictions on user entry.
**** [ ] Possibly auto-log an issue to the project when they do so.
** [ ] Recognized acronyms should be formatted (colored?) differently when displaying definitions.
* [ ] Export to dictionary command, for exporting selected acronyms to a dictionary that tools like cSpell can use.
